### PR TITLE
BUGFIX: MSF-17392 force encoding enable for utf-8

### PR DESCRIPTION
**Pull request by tqtu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/salesforce_bulk_query-fossa-scanning-oss-zuul-el7/1/ : SUCCESS in 13s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/salesforce_bulk_query-oss-check/2/ : SUCCESS in 3s

**Pull request merged**
