### PR TITLE
FEATURE: MSF-24697 remove limit depencency json package

### PR DESCRIPTION
**Pull request by tqtu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- salesforce_bulk_query-fossa-scanning-oss-zuul : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/salesforce_bulk_query-merge-compliance-check/3/ : FAILURE in 15s

**Comment by vietnguyenkim-gooddata** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/salesforce_bulk_query-fossa-scanning-oss-zuul/1/ : SUCCESS in 2m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/salesforce_bulk_query-merge-compliance-check/4/ : SUCCESS in 13s

**Pull request merged**
